/*
 * Copyright MediaZ Teknoloji A.S. All Rights Reserved.
 */

#pragma once
#include <Nodos/Plugin.hpp>

NOS_REGISTER_NAME(In)
NOS_REGISTER_NAME(Out)
NOS_REGISTER_NAME(ServerIP)
NOS_REGISTER_NAME(StreamerID)
NOS_REGISTER_NAME(MaxFPS)
NOS_REGISTER_NAME(WebRTCPlayer);
NOS_REGISTER_NAME(WebRTCStreamer);
NOS_REGISTER_NAME(TargetBitrate);
NOS_REGISTER_NAME(UseHttps);

NOS_REGISTER_NAME(RGBtoYUV420_Compute_Shader);
NOS_REGISTER_NAME(RGBtoYUV420_Compute_Pass);
NOS_REGISTER_NAME(YUV420toRGB_Compute_Shader);
NOS_REGISTER_NAME(YUV420toRGB_Compute_Pass);
NOS_REGISTER_NAME(Input);
NOS_REGISTER_NAME(Output);
NOS_REGISTER_NAME(PlaneY);
NOS_REGISTER_NAME(PlaneU);
NOS_REGISTER_NAME(PlaneV);