#pragma once

#include <Nodos/Name.hpp>

namespace nos::reflect
{
NOS_REGISTER_NAME(Value)
NOS_REGISTER_NAME(Make)
NOS_REGISTER_NAME(MakeDynamic)
NOS_REGISTER_NAME(A)
NOS_REGISTER_NAME(B)
NOS_REGISTER_NAME(IndexOf)
NOS_REGISTER_NAME(InputArray)
NOS_REGISTER_NAME(Index)
NOS_REGISTER_NAME(Indexer)
NOS_REGISTER_NAME(Delay)
NOS_REGISTER_NAME_SPACED(TextureTypeName, "nos.sys.vulkan.Texture")
NOS_REGISTER_NAME_SPACED(BufferTypeName, "nos.sys.vulkan.Buffer")
NOS_REGISTER_NAME(Break)
NOS_REGISTER_NAME(Array)
NOS_REGISTER_NAME(Arithmetic)
NOS_REGISTER_NAME(ArithmeticDynamic)
NOS_REGISTER_NAME(ScalarArithmetic)
NOS_REGISTER_NAME(Scalar)
NOS_REGISTER_NAME(Output)
NOS_REGISTER_NAME(Input)
NOS_REGISTER_NAME_SPACED(TypeNameGeneric, "nos.Generic")
NOS_REGISTER_NAME_SPACED(DictTypeName, "nos.Dict")
NOS_REGISTER_NAME(IsEqual)
NOS_REGISTER_NAME(GreaterThan)
NOS_REGISTER_NAME(LessThan)
NOS_REGISTER_NAME(IsLess)
NOS_REGISTER_NAME(IsGreater)
NOS_REGISTER_NAME(Size)
}